### ISSUE TITLE
Getting runtime error with this command

### ISSUE THREAD

**Issue by tayabsoomro** [yeban/ncbi-blast-dbs#10]
I am trying to download `nr` using `~/bin/ncbi-blast-dbs nr` database but I get this error somewhere in the output:

```
.
.
.
2020-01-07 12:56:50 (2.62 MB/s) - ‘nr.122.tar.gz.md5’ saved [48/48]

nr.122.tar.gz: OK
tar xvf nr.122.tar.gz
nr.pal
nr.122.pin
nr.122.phr
nr.131.pni
nr.131.pnd
nr.131.psi
nr.131.psd
nr.131.ppi
nr.131.ppd
nr.131.phi
nr.131.phd
nr.131.pog
taxdb.btd
taxdb.bti
nr.122.psq
nr.122.pni
nr.122.pnd
nr.122.psi
nr.122.psd
nr.122.ppi
nr.122.ppd
nr.122.phi
nr.122.phd
nr.122.pog
taxdb.btd
taxdb.bti
/home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (2): [tar xvf nr.127.tar.gz...] (RuntimeError)
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `call'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `sh'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:37:in `sh'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/ncbi-blast-dbs-0.0.6/lib/ncbi-blast-dbs.rake:21:in `block in download'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `call'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `sh'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:37:in `sh'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/ncbi-blast-dbs-0.0.6/lib/ncbi-blast-dbs.rake:17:in `download'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/ncbi-blast-dbs-0.0.6/lib/ncbi-blast-dbs.rake:47:in `block (3 levels) in <top (required)>'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
        from /usr/share/ruby/monitor.rb:211:in `mon_synchronize'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/task.rb:211:in `block (2 levels) in invoke_prerequisites_concurrently'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/promise.rb:63:in `call'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/promise.rb:63:in `chore'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/promise.rb:45:in `work'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/thread_pool.rb:105:in `process_queue_item'
        from /home/AAFC-AAC/soomrot/.gem/ruby/gems/rake-10.5.0/lib/rake/thread_pool.rb:125:in `block (2 levels) in start_thread'
```

What does status code 2 refer to?

**Comment by yeban** [comment]
The status code 2 is most likely coming from the `tar` command which means fatal error. Maybe you ran out of space in the directory you are downloading the BLAST database? Another possible explanation is that somehow more than one threads are trying to download the same volume, and output of one overwrites the other. This possibility was highlighted in #9, and is a bug that needs fixing. A final possibility is that the volume nr.127.tar.gz was corrupted due to network error. In this case rerunning the command should take care of the corrupted download.

**Comment by dbx-git** [comment]
I also had the same situation, and I was sure it was not caused by lack of space, and I don’t know what caused it.
