### ISSUE TITLE
error when downloading nr...

### ISSUE THREAD

**Issue by IsmailM** [yeban/ncbi-blast-dbs#5]
am seeing this error repeatedly when running:

```
nice -n 10 genevalidator ncbi-blast-dbs nr
```

```
tar: Exiting with failure status due to previous errors
/home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (2): [tar xvf nr.91.tar.gz...] (RuntimeError)
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `call'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `sh'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:37:in `sh'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/ncbi-blast-dbs-0.0.6/lib/ncbi-blast-dbs.rake:21:in `block in download'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `call'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `sh'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:37:in `sh'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/ncbi-blast-dbs-0.0.6/lib/ncbi-blast-dbs.rake:17:in `download'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/ncbi-blast-dbs-0.0.6/lib/ncbi-blast-dbs.rake:47:in `block (3 levels) in <top (required)>'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
        from /home/ucbtmog/d/b/genevalidator/lib/ruby/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:211:in `block (2 levels) in invoke_prerequisites_concurrently'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/promise.rb:63:in `call'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/promise.rb:63:in `chore'
nr.103.phd
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/promise.rb:45:in `work'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/thread_pool.rb:105:in `process_queue_item'
        from /home/ucbtmog/d/b/genevalidator/lib/vendor/ruby/2.2.0/gems/rake-10.5.0/lib/rake/thread_pool.rb:125:in `block (2 levels) in start_thread'
```

**Comment by IsmailM** [comment]
deffo not either of those issues (have a few tbs left of space and it would at least get half way through downloading before giving me the error)...

But interestingly, after seeing this error 4 times consecutively, I then edited the source code with the #7, to make the logging better so I could see what was happening... And this error immediately disappeared. I also checked with `update_blast.pl` and it said everything was up-to-date. 

The only reason I can think of is that maybe multiple sub-processes were writing to STDOUT at the same time (which wouldn't normally an issue)???
